name: Deployment

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add SSH Key
      run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "${{secrets.DEPLOY_KEY}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Configure SSH connection
      run: |
        echo "Host ${{secrets.DEPLOY_HOST}}\n  Hostname ${{secrets.DEPLOY_HOST}}\n  User ${{secrets.DEPLOY_USER}}\n  Port ${{secrets.DEPLOY_PORT}}\n IdentityFile ~/.ssh/id_rsa" > ~/.ssh/config
        chmod 600 ~/.ssh/config

    - name: Sync wp-content directory
      run: rsync -chav --delete --exclude /.git/ --exclude /.github/ ./ ${{secrets.DEPLOY_HOST}}:${{secrets.DEPLOY_PATH}}
